export enum HttpStatusEnum {
  OK = 200,
  CREATED = 201,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500
}

export enum ErrorCode {
  USER_NOT_FOUND,
  VEHICLE_NOT_FOUND,
  COST_NOT_FOUND,
  FINANCE_NOT_FOUND,
  SUMMARY_NOT_FOUND,
  SALE_NOT_FOUND,
  BAD_REQUEST,
  UNAUTHORIZED,
  FORBIDDEN,
  INTERNAL_ERROR,
}